name: Continuous Delivery

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build and test
        run: |
          npm install
          npm run build
          npm test

      - name: Deploy to GitHub Pages
        run: |
          npm run deploy
